export const Users = [
    {
        id:1,
        profilePicture: "/assets/person/1.jpeg",
        username: "Tahiri med",
    },
    {
        id:2,
        profilePicture: "/assets/person/2.jpeg",
        username: "Tahiri abdelhak",
    },
    {
        id:3,
        profilePicture: "/assets/person/3.jpeg",
        username: "Tahiri maroua",
    },
    {
        id:4,
        profilePicture: "/assets/person/4.jpeg",
        username: "Tahiri hala",
    },
    {
        id:5,
        profilePicture: "/assets/person/5.jpeg",
        username: "Tahiri douaa",
    },
    {
        id:6,
        profilePicture: "/assets/person/6.jpeg",
        username: "Tahiri salah",
    },
    {
        id:7,
        profilePicture: "/assets/person/7.jpeg",
        username: "Fatima Ezzahra Assou",
    },
    {
        id:8,
        profilePicture: "/assets/person/8.jpeg",
        username: "Assou Moulodi",
    },
    {
        id:9,
        profilePicture: "/assets/person/9.jpeg",
        username: "Mounim Aicha",
    },
    {
        id:10,
        profilePicture: "/assets/person/10.jpeg",
        username: "Assou Nabil",
    },
]

export const Posts = [
    {
        id:1,
        desc: "Love for all, hatred for nono.",
        photo: "/assets/post/1.jpeg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id:2,
        desc: "Love for all, hatred for nono.",
        photo: "/assets/post/2.jpeg",
        date: "5 mins ago",
        userId: 7,
        like: 95,
        comment: 7,
    },
    {
        id:3,
        desc: "Love for all, hatred for nono.",
        photo: "/assets/post/3.jpeg",
        date: "5 mins ago",
        userId: 6,
        like: 78,
        comment: 3,
    },
    {
        id:4,
        desc: "Love for all, hatred for nono.",
        photo: "/assets/post/4.jpeg",
        date: "5 mins ago",
        userId: 9,
        like: 28,
        comment: 19,
    },
    {
        id:5,
        desc: "Love for all, hatred for nono.",
        photo: "/assets/post/5.jpeg",
        date: "5 mins ago",
        userId: 4,
        like: 98,
        comment: 36,
    },
    {
        id:6,
        desc: "Love for all, hatred for nono.",
        photo: "/assets/post/6.jpeg",
        date: "5 mins ago",
        userId: 3,
        like: 321,
        comment: 29,
    },
    {
        id:7,
        desc: "Love for all, hatred for nono.",
        photo: "/assets/post/7.jpeg",
        date: "15 mins ago",
        userId: 1,
        like: 22,
        comment: 4,
    },
    {
        id:8,
        desc: "Love for all, hatred for nono.",
        photo: "/assets/post/8.jpeg",
        date: "5 hour ago",
        userId: 3,
        like: 322,
        comment: 19,
    },
    {
        id:9,
        desc: "Love for all, hatred for nono.",
        photo: "/assets/post/9.jpeg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id:10,
        desc: "Love for all, hatred for nono.",
        photo: "/assets/post/10.jpeg",
        date: "48 mins ago",
        userId: 2,
        like: 152,
        comment: 1,
    },
]